name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: App Settings Variable Substitution
      uses: microsoft/variable-substitution@v1
      with:
        files: 'AppSettingsYamlTest/AppSettingsYamlTest.Tests/appsettings2.json'
      env:
        AppSettings.MySecret2: "2020 is the worst year"
    - name: Run automated unit and integration tests
      run: dotnet test AppSettingsYamlTest/AppSettingsYamlTest.Tests/AppSettingsYamlTest.Tests.csproj --configuration Release 

